Pole balancing simulation in Drake
StanfordASL/neural-network-lyapunov pull request #406
Opened 2021-12-08 03:29 UTC by lujieyang

2021-12-08 06:41 UTC, hongkai-dai requested changes
You can locally fun`flake8` to check the linting of your code. To fix the linting error, I often run `yapf` on the file, and then manually fix the remaining linting errors.

Checkpoint.

> Reviewed 8 of 10 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-:-MqNfCQ99DwxIe5mCOUG:b-o1ykb7)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @hongkai-dai and @lujieyang)

___
*[neural_network_lyapunov/examples/pole/simulation/A.npy, line 0 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNfOefEZPlQjztSITh:-MqNfOefEZPlQjztSITi:bag0y0x) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/A.npy#L0)):*
It is better not to put binary files on github. I think you can easily compute `A`, `B` matrix with our code, so there is not really an advantage to compute this linearization and store them.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 38 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNfu2X0ELlRA0otKLc:-MqNfu2X0ELlRA0otKLd:b-khfb0m) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L38)):*
> ```Python
> 
>         self.pole_state_input_port = self.DeclareInputPort(
>             "pole_state", PortDataType.kVectorValued, 13)
> ```

Why the pole state has dimension 13? I think the pole state is the end-effector velocity, the delta position between the end-effector and the pole, and the pole velocity, so it should have 7 states. It is better to explain the input in the class documentation.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 63 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNhWUR-ZE2fNxXBwvy:-MqNhWUR-ZE2fNxXBwvz:b-bosg94) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L63)):*
> ```Python
>         self.dt = 0.01
>         self.u_dim = 3
>         self.Ac = np.array([[0., 0., 0., 0., 0., 1., 0.],
> ```

You can compute this Ac and Bc matrix pretty easily by instantiating a `Pole` system and call its `gradient` function.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 81 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNgbdP5aK0B8Qm_gU-:-MqNgbdP5aK0B8Qm_gU0:b-j4z4s1) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L81)):*
> ```Python
>         self.Q = np.diag([10, 10, 1, 1, 1, 10, 10])
>         self.R = np.eye(3)
>         self.K, _ = DiscreteTimeLinearQuadraticRegulator(self.Ad, self.Bd, self.Q,
> ```

Why using the discrete LQR instead of the continuous LQR? I would think we can use the continuous LQR directly. When you compute the discrete-time A, B matrix, you assume explicit Euler integration, which isn't really how Drake does time integration, so I think this discrete-time A, B aren't correct.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 84 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNiiXt6L4yK1rRv0VY:-MqNiiXt6L4yK1rRv0VZ:bimbq4s) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L84)):*
> ```Python
>                                                       self.R)
> 
>         self.pole_state_input_port = self.DeclareInputPort(
> ```

I don't see `pole_state_input_port` being used.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 87 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNi1UJEtzCaFCBc_H2:-MqNi1UJEtzCaFCBc_H3:bypkazr) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L87)):*
> ```Python
>             "pole_state", PortDataType.kVectorValued, 13)
>         self.iiwa_state_input_port = self.DeclareInputPort(
>             "iiwa_state", PortDataType.kVectorValued, 14)
> ```

Why we need this iiwa_state port?
___
*[neural_network_lyapunov/examples/pole/simulation/utils.py, line 20 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNjssh5M3QWGjJ23ml:-MqNjssh5M3QWGjJ23mm:b-axizmh) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/utils.py#L20)):*
> ```Python
> 
> X_L7E = RigidTransform(
>     RollPitchYaw(np.pi / 2, 0, np.pi / 2), np.array([0, 0, 0.114]))
> ```

This is different from the `l7_ee_offset` defined in `iiwa_and_plate.yaml`. Could you explain why? If they do mean the same thing, then I would prefer to defining it only in `iiwa_and_plate.yaml`, and read the rigid transform from yaml file.
___
*[neural_network_lyapunov/examples/pole/simulation/utils.py, line 51 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNjS5I2v0VCjbgwOtg:-MqNjS5I2v0VCjbgwOth:b-ee91y4) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/utils.py#L51)):*
> ```Python
>     plant.mutable_gravity_field().set_gravity_vector(gravity)
> 
>     if add_schunk_inertia:
> ```

I thought we won't add schunk to the iiwa, but physically weld the end effector to the wrist link?
___
*[neural_network_lyapunov/examples/pole/simulation/models/pole.sdf, line 5 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNkdjw0VAkyDwWY9KW:-MqNkdjw0VAkyDwWY9KX:b9zzkp3) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/models/pole.sdf#L5)):*
> ```
> 
>   <!-- Note:
>        This file defines the model for a pole with the ball attached to one end
> ```

This file is named as`pole.sdf` but contains both pole and the ball. We also have another `pole_and_ball.sdf` that also contains both the pole and the ball. It is confusing to keep very similar files.

I think the confusion part is that we the pole will have one ball with a certain mass on one of its end, and another tiny massless ball on the other end to make contact with the end effector. So I would suggest one of the options
1. Remove this file, if we always use the pole with a sphere (of certain mass).
2. Change this documentation, to indicate that the ball is tiny and massless, it is only used to make point contact with the end-effector.


<!-- Sent from Reviewable.io -->

2021-12-08 16:04 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/utils.py, line 51 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNjS5I2v0VCjbgwOtg:-MqPmOrF1ZG2Nc441BBj:b-c982gw) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/utils.py#L51)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I thought we won't add schunk to the iiwa, but physically weld the end effector to the wrist link?
</blockquote></details>

Sure, I will delete this function.


<!-- Sent from Reviewable.io -->

2021-12-08 16:05 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 81 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNgbdP5aK0B8Qm_gU-:-MqPmb3d9NqCyj6OF7Vm:bn0px3n) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L81)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why using the discrete LQR instead of the continuous LQR? I would think we can use the continuous LQR directly. When you compute the discrete-time A, B matrix, you assume explicit Euler integration, which isn't really how Drake does time integration, so I think this discrete-time A, B aren't correct.
</blockquote></details>

I see. Changing to continuous LQR


<!-- Sent from Reviewable.io -->

2021-12-08 16:08 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 84 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNiiXt6L4yK1rRv0VY:-MqPnIUQBlF8croYZh_c:bhofej8) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L84)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't see `pole_state_input_port` being used.
</blockquote></details>

Deleted


<!-- Sent from Reviewable.io -->

2021-12-08 16:08 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 87 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNi1UJEtzCaFCBc_H2:-MqPnLInBHqKNbI0RG1N:b-mgn5cx) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L87)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why we need this iiwa_state port?
</blockquote></details>

Port deleted


<!-- Sent from Reviewable.io -->

2021-12-08 16:11 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/utils.py, line 20 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNjssh5M3QWGjJ23ml:-MqPnijC9zkYh9deegu0:b-1u94rc) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/utils.py#L20)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This is different from the `l7_ee_offset` defined in `iiwa_and_plate.yaml`. Could you explain why? If they do mean the same thing, then I would prefer to defining it only in `iiwa_and_plate.yaml`, and read the rigid transform from yaml file.
</blockquote></details>

We are not using the schunk so I'm deleting the definition. I just cleaned up the code a bit to remove dependencies on the utils.py (this file has a lot of extra functionalities that we don't need)


<!-- Sent from Reviewable.io -->

2021-12-08 16:28 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 63 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNhWUR-ZE2fNxXBwvy:-MqPrl6VE5Bx7PXihv1s:b-2n1845) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L63)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

You can compute this Ac and Bc matrix pretty easily by instantiating a `Pole` system and call its `gradient` function.
</blockquote></details>

I calculated Ac, Bc offline. Would you recommend do it here instead?


<!-- Sent from Reviewable.io -->

2021-12-08 16:57 UTC, hongkai-dai requested changes
> Reviewed 3 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @hongkai-dai and @lujieyang)

___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 63 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNhWUR-ZE2fNxXBwvy:-MqPyC9o-26OjnIvGBrl:bsvhisg) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L63)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

I calculated Ac, Bc offline. Would you recommend do it here instead?
</blockquote></details>

I would recommend to put the code computing Ac, Bc here, so that in the future, if we update any parameters, like the mass of the plate, or the length of the pole, the Ac, Bc matrices get updated automatically.


<!-- Sent from Reviewable.io -->

2021-12-08 20:09 UTC, lujieyang reviewed
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: 8 of 10 files reviewed, 3 unresolved discussions (waiting on @hongkai-dai)

___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 38 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNfu2X0ELlRA0otKLc:-MqPnTQfAe6AnRmrlBBS:b-mgn5cx) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L38)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Why the pole state has dimension 13? I think the pole state is the end-effector velocity, the delta position between the end-effector and the pole, and the pole velocity, so it should have 7 states. It is better to explain the input in the class documentation.
</blockquote></details>

Port deleted
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 63 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNhWUR-ZE2fNxXBwvy:-MqQeZeAAm5iQjWuCHyk:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L63)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I would recommend to put the code computing Ac, Bc here, so that in the future, if we update any parameters, like the mass of the plate, or the length of the pole, the Ac, Bc matrices get updated automatically.
</blockquote></details>

Done.
___
*[neural_network_lyapunov/examples/pole/simulation/models/pole.sdf, line 5 at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNkdjw0VAkyDwWY9KW:-MqPkAnO5MfK8vnUPz7V:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/models/pole.sdf#L5)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This file is named as`pole.sdf` but contains both pole and the ball. We also have another `pole_and_ball.sdf` that also contains both the pole and the ball. It is confusing to keep very similar files.

I think the confusion part is that we the pole will have one ball with a certain mass on one of its end, and another tiny massless ball on the other end to make contact with the end effector. So I would suggest one of the options
1. Remove this file, if we always use the pole with a sphere (of certain mass).
2. Change this documentation, to indicate that the ball is tiny and massless, it is only used to make point contact with the end-effector.
</blockquote></details>

Done.
___
*[neural_network_lyapunov/examples/pole/simulation/A.npy, line  at r1](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqNfOefEZPlQjztSITh:-MqPjTp02IQLxWJEc4hG:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/3d647d27bee9a4503960981b9bd39cdcde941014/neural_network_lyapunov/examples/pole/simulation/A.npy#L)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

It is better not to put binary files on github. I think you can easily compute `A`, `B` matrix with our code, so there is not really an advantage to compute this linearization and store them.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-08 22:36 UTC, hongkai-dai requested changes
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: 8 of 10 files reviewed, 8 unresolved discussions (waiting on @hongkai-dai and @lujieyang)

___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 53 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR5zgH0mLlwiRS7kqn:-MqR5zgH0mLlwiRS7kqo:b-fdlqyl) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L53)):*
> ```Python
>         self.pose_input_port = self.DeclareAbstractInputPort(
>             "body_pose", AbstractValue.Make([RigidTransform()]))
>         self.velocity_input_port = self.DeclareAbstractInputPort(
> ```

Could you rename this to `body_velocity_input_port`? `velocity` could mean either joint velocity (generalized velocity) or body velocity.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 141 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR6kRGEXinAr84ik3n:-MqR6kRHBHE3YvxcSS9c:b3in4xp) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L141)):*
> ```Python
>     plate_frame = plant_robot.GetBodyByName("box").body_frame()
> 
>     p_WQ = plate_position
> ```

Could you document that `Q` stands for plate frame? And just curious, why this frame is abbreviated as `Q`?
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 197 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqRBFBS5fdZ8JTZvPoL:-MqRBFBS5fdZ8JTZvPoM:b-95197p) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L197)):*
> ```Python
> 
> def run_sim(gravity: np.array,
>             f_C_W,
> ```

Could you document what f_C_W is?
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 198 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqRBCYlEEyuUoyQwEux:-MqRBCYlEEyuUoyQwEuy:btny9mu) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L198)):*
> ```Python
> def run_sim(gravity: np.array,
>             f_C_W,
>             time_step,
> ```

time_step is not used?
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 204 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR75Ds1KH1CYqfMTMl:-MqR75Ds1KH1CYqfMTMm:b-ibr7zi) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L204)):*
> ```Python
> 
>     # MultibodyPlant
>     plant = MultibodyPlant(0)
> ```

Could you explain a bit why the simulation is continuous time here? The IIWA controller is a discrete time system.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 253 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR7rKN3pkAzTQVSaIk:-MqR7rKO1V1lgWK_Fr5Z:b-pvn7lo) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L253)):*
> ```Python
>     # Logs
>     iiwa_log = LogOutput(plant.get_state_output_port(iiwa_model), builder)
>     iiwa_log.set_publish_period(0.001)
> ```

Do you intend to make this dt the same as the iiwa controller dt? If yes, then
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 292 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqRAy935SmUJXV0AW9Y:-MqRAy935SmUJXV0AW9Z:b-ciom1o) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L292)):*
> ```Python
>     f_C_W = np.array([0, 0, -20])
>     # Stiffness matrix of the robot.
>     Kp_iiwa = np.array([800., 600, 600, 600, 400, 200, 200])
> ```

Unused?


<!-- Sent from Reviewable.io -->

2021-12-09 02:44 UTC, hongkai-dai requested changes
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: 8 of 10 files reviewed, 8 unresolved discussions (waiting on @hongkai-dai and @lujieyang)

___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 253 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR7rKN3pkAzTQVSaIk:-MqS3jaA4djwXuW_Gc8X:b-sfw12a) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L253)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Do you intend to make this dt the same as the iiwa controller dt? If yes, then
</blockquote></details>

then instead of using the magic number 0.001 here, I think it is better to use `dt` as an input to this function, and every system (including the logger, controller iiwa, and the simulated iiwa) all use this `dt` in the construction.


<!-- Sent from Reviewable.io -->

2021-12-09 19:54 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 204 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR75Ds1KH1CYqfMTMl:-MqVj7bx-z0CkJzs3Fbq:bgqarxp) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L204)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you explain a bit why the simulation is continuous time here? The IIWA controller is a discrete time system.
</blockquote></details>

When I try to use discrete time step for MultibodyPlant, Drake gives the error "MultibodyPlant's discrete update solver failed to converge at simulation time =  0.00035 with discrete update period =   1e-05. This usually means that the plant's discrete update period is too large to resolve the system's dynamics for the given simulation conditions. This is often the case during abrupt collisions or during complex and fast changing contact configurations. Another common cause is the use of high gains in the simulation of closed loop systems. These might cause numerical instabilities given our discrete solver uses an explicit treatment of actuation inputs. Possible solutions include: switch to a continuous model (discrete update period is zero)."

The collision might be due to the initial impact of the pole with the plate.


<!-- Sent from Reviewable.io -->

2021-12-09 19:56 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 141 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR6kRGEXinAr84ik3n:-MqVl0oOEd-LD1335ivU:b-coed2x) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L141)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you document that `Q` stands for plate frame? And just curious, why this frame is abbreviated as `Q`?
</blockquote></details>

Done. 

I was borrowing code from the IK tutorial for the manipulation class.


<!-- Sent from Reviewable.io -->

2021-12-09 23:40 UTC, lujieyang reviewed
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: 8 of 10 files reviewed, 8 unresolved discussions (waiting on @hongkai-dai and @lujieyang)

___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 53 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR5zgH0mLlwiRS7kqn:-MqViKkf1B0XGIhYvCrb:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L53)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you rename this to `body_velocity_input_port`? `velocity` could mean either joint velocity (generalized velocity) or body velocity.
</blockquote></details>

Done.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 198 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqRBCYlEEyuUoyQwEux:-MqVl97b3eqchAekt5Vf:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L198)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

time_step is not used?
</blockquote></details>

Done.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 253 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR7rKN3pkAzTQVSaIk:-MqVkefHDlV0UTErN3y0:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L253)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

then instead of using the magic number 0.001 here, I think it is better to use `dt` as an input to this function, and every system (including the logger, controller iiwa, and the simulated iiwa) all use this `dt` in the construction.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-10 03:46 UTC, hongkai-dai requested changes
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: 8 of 10 files reviewed, 9 unresolved discussions (waiting on @hongkai-dai and @lujieyang)

___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 53 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR5zgH0mLlwiRS7kqn:-MqXQ4dmCfWTwLfWE_mQ:bx4yr6n) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L53)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I don't see the change yet?
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 141 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR6kRGEXinAr84ik3n:-MqXQDc-CY8__bvnBgv7:bvdmboc) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L141)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

Done. 

I was borrowing code from the IK tutorial for the manipulation class.

</blockquote></details>

I don't see the change yet? I think this part either requires a documentation on where that point `Q` is, or rename it to `p_WP` as `P` stands for plate.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 204 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR75Ds1KH1CYqfMTMl:-MqXQ_lFCXrHmwhqKkSa:b-7hx3sw) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L204)):*
<details><summary><i>Previously, lujieyang wrote…</i></summary><blockquote>

When I try to use discrete time step for MultibodyPlant, Drake gives the error "MultibodyPlant's discrete update solver failed to converge at simulation time =  0.00035 with discrete update period =   1e-05. This usually means that the plant's discrete update period is too large to resolve the system's dynamics for the given simulation conditions. This is often the case during abrupt collisions or during complex and fast changing contact configurations. Another common cause is the use of high gains in the simulation of closed loop systems. These might cause numerical instabilities given our discrete solver uses an explicit treatment of actuation inputs. Possible solutions include: switch to a continuous model (discrete update period is zero)."

The collision might be due to the initial impact of the pole with the plate.
</blockquote></details>

I see, I think then we need to modify the initial state of the system, such that the pole starts on the state. If you tried discrete update period = 1e-5 (which is a tiny step) and the simulation still fails, that means the simulation has an inherent problem. Switching to continuous time solver isn't the best way to solve this inherent problem.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 271 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqXRJaU8TTH1A_2BKR5:-MqXRJaU8TTH1A_2BKR6:b-reqmen) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L271)):*
> ```Python
>     plant.SetPositions(context_plant, iiwa_model, q0)
>     plant.SetPositions(context_plant, pole_model, np.array(
>         [0, 0, 0, 1, 0.7, 0, 0.3 + 0.41 + 0.003]))
> ```

This orientation of the pole is a big weird. It is rotating about the z axis by 180 degrees. Are you sure it should be [0, 0, 0, 1] instead of [1, 0, 0, 0]?


<!-- Sent from Reviewable.io -->

2021-12-10 19:47 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 292 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqRAy935SmUJXV0AW9Y:-Mq_sdhhD4K0mq4CXHVH:bpeph98) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L292)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Unused?
</blockquote></details>

Currently used in building the MBP for iiwa controller (not implemented)


<!-- Sent from Reviewable.io -->

2021-12-11 02:49 UTC, hongkai-dai reviewed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/> 

> Reviewed 1 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-:-MqbOFm51VOj7aYAYtJ5:bg7igkv)* status: 9 of 10 files reviewed, 1 unresolved discussion (waiting on @hongkai-dai and @lujieyang)



<!-- Sent from Reviewable.io -->

2021-12-11 02:51 UTC, hongkai-dai reviewed
> Reviewed 1 of 1 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @hongkai-dai)



<!-- Sent from Reviewable.io -->

2021-12-11 02:54 UTC, hongkai-dai reviewed
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @hongkai-dai)

___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 197 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqbOr35-VFFs1wfpc-w:-MqbOr35-VFFs1wfpc-x:b-czr60v) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L197)):*
> ```Python
> 
> def run_sim(gravity: np.array,
>             f_C_W,
> ```

BTW, I don't think we have explained what `C` means here? Maybe document it that `C` is the point on the end effector where the pole makes contact on the end-effector, and `f_C_W` is the force applied from the pole to the end-effector at point C, and the force is measured in the world frame `W`.

The reason to add this documentation is to make it clear where the force is applied, and who applies that force (since there is an equal and opposite force from the end-effector to the pole at the same point).


<!-- Sent from Reviewable.io -->

2021-12-11 03:45 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 197 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqbOr35-VFFs1wfpc-w:-MqbZeJO1wWmWb4oa3Nk:b-8u2ffh) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L197)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

BTW, I don't think we have explained what `C` means here? Maybe document it that `C` is the point on the end effector where the pole makes contact on the end-effector, and `f_C_W` is the force applied from the pole to the end-effector at point C, and the force is measured in the world frame `W`.

The reason to add this documentation is to make it clear where the force is applied, and who applies that force (since there is an equal and opposite force from the end-effector to the pole at the same point).
</blockquote></details>

I'm removing f_C_W as a whole because we will later add the iiwa controller.


<!-- Sent from Reviewable.io -->

2021-12-11 03:45 UTC, lujieyang commented
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 197 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqRBFBS5fdZ8JTZvPoL:-Mq_sn69DswBki9XyfWe:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L197)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

Could you document what f_C_W is?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-11 03:46 UTC, lujieyang reviewed
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: 9 of 10 files reviewed, all discussions resolved (waiting on @hongkai-dai)

___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 53 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR5zgH0mLlwiRS7kqn:-Mq_spQL3jb-Eu0kopQl:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L53)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't see the change yet?
</blockquote></details>

Done.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 141 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR6kRGEXinAr84ik3n:-Mq_sokw33uLw3Ro32i3:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L141)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I don't see the change yet? I think this part either requires a documentation on where that point `Q` is, or rename it to `p_WP` as `P` stands for plate.
</blockquote></details>

Done.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 204 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqR75Ds1KH1CYqfMTMl:-Mq_3o9U6vPOt6eJ6m-0:b-e1vauw) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L204)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

I see, I think then we need to modify the initial state of the system, such that the pole starts on the state. If you tried discrete update period = 1e-5 (which is a tiny step) and the simulation still fails, that means the simulation has an inherent problem. Switching to continuous time solver isn't the best way to solve this inherent problem.
</blockquote></details>

Got it! I changed the pole's initial condition to be slightly above the plate and the simulation is working now.
___
*[neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py, line 271 at r4](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406#-MqXRJaU8TTH1A_2BKR5:-Mq_sk_9BZHLuDCYNSBN:b-896fix) ([raw file](https://github.com/stanfordasl/neural-network-lyapunov/blob/765c393384cf5c70a880ebb5c65b10f78661acd0/neural_network_lyapunov/examples/pole/simulation/pole_balancing_sim.py#L271)):*
<details><summary><i>Previously, hongkai-dai (Hongkai Dai) wrote…</i></summary><blockquote>

This orientation of the pole is a big weird. It is rotating about the z axis by 180 degrees. Are you sure it should be [0, 0, 0, 1] instead of [1, 0, 0, 0]?
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-12-11 03:58 UTC, hongkai-dai approved these changes
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/stanfordasl/neural-network-lyapunov/406)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lujieyang)



<!-- Sent from Reviewable.io -->

2021-12-11 03:58 UTC, merged